import { useState } from 'react';
import { LockKeyhole, Mail, Trophy } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';

export function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const auth = useAuth(); const navigate = useNavigate();
  async function submit(e: React.FormEvent) { e.preventDefault(); try { await auth.login.mutateAsync({ email, password }); navigate('/'); } catch {} }
  return <main className="min-h-dvh bg-white px-5 pt-[max(2rem,env(safe-area-inset-top))] text-black"><div className="mx-auto max-w-md"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#073B8C] text-white shadow-md"><Trophy /></div><h1 className="mt-7 text-3xl font-black tracking-tight">Entrar no Chavea</h1><p className="mt-2 text-sm font-medium text-slate-500">Sua arena de campeonatos começa aqui.</p><form onSubmit={submit} className="mt-8 space-y-4"><label className="block text-sm font-bold">E-mail<div className="mt-2 flex min-h-14 items-center gap-3 rounded-2xl border border-slate-200 px-4 focus-within:border-[#073B8C]"><Mail className="h-5 w-5 text-slate-400"/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="w-full outline-none" placeholder="voce@email.com"/></div></label><label className="block text-sm font-bold">Senha<div className="mt-2 flex min-h-14 items-center gap-3 rounded-2xl border border-slate-200 px-4 focus-within:border-[#073B8C]"><LockKeyhole className="h-5 w-5 text-slate-400"/><input type="password" required minLength={10} value={password} onChange={e=>setPassword(e.target.value)} className="w-full outline-none" placeholder="Sua senha"/></div></label>{auth.login.isError&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-[#E31B23]">E-mail ou senha inválidos.</p>}<button disabled={auth.login.isPending} className="min-h-14 w-full rounded-2xl bg-[#073B8C] font-extrabold text-white shadow-md disabled:opacity-60">{auth.login.isPending?'Entrando…':'Entrar'}</button></form><div className="my-6 flex items-center gap-3 text-xs font-bold text-slate-400"><span className="h-px flex-1 bg-slate-200"/>OU<span className="h-px flex-1 bg-slate-200"/></div><a href={auth.googleLoginUrl} className="flex min-h-14 items-center justify-center rounded-2xl border border-slate-200 bg-white font-bold shadow-sm">Continuar com Google</a><p className="mt-7 text-center text-sm text-slate-500">Ainda não tem conta? <Link to="/register" className="font-extrabold text-[#073B8C]">Criar conta</Link></p></div></main>;
}
